### PR TITLE
Add missing param test for pam_d_sshd_template

### PR DESCRIPTION
**Pull request by Phil-Friderici**
suggestion only

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
seems that the regex for the failing messages is fishy. Looking at my commit you will see that I took the wrong error message but it still works. Think that the pipes needs to get escaped as well.

Will test and update it here.

**Comment by Phil-Friderici** [comment]
now Ruby 1.8 hates me :/

**Comment by boandersson** [comment]
Thanks! I think your test should replace the one before it - "with pam_d_sshd_template set to pam/sshd.custom.erb without specifying all pam_sshd_*" - if you agree I can remove that one once ruby 1.8 starts to like you again ;)

I also would use the same coding style as the rest of the code, e.g use class 'pam' instead of subject, regexps using // instead of %r but it's not really my call :)

**Comment by Phil-Friderici** [comment]
Yes, this test have the potential to succeed the earlier one.
This time I expect Ruby 1.8.7 to accept it. So go Travis proof me being right ;)

If everything works well fell free to squash all the code into one commit to allow merging in upstream.

btw: have a nice weekend @boandersson

**Pull request merged**
